### ISSUE TITLE
Switch default format to YAML?

### ISSUE THREAD

**Issue by felicianotech** [strawberry-tools/strawberry-v0#40]
Gotham (Hugo) supports three config formats. YAML, TOML, and JSON. While all three are supported, Hugo's default format when running `hugo new site`, in Docs, in tests, etc seems to be TOML.

Most dev tools I know use YAML by default. To name a few: CircleCI, Travis CI, Kubernetes, Terraform, Jekyll, and GitHub Actions.

@mibragimchayev Thoughts on making our default YAML?

Ref:

YAML: https://yaml.org/
TOML: https://github.com/toml-lang/toml
JSON: https://www.json.org/json-en.html

YAML vs TOML example: https://gist.github.com/oconnor663/9aeb4ed56394cb013a20

---

Sections:

- [x] new site
- [ ] new theme
- [x] global flags

**Comment by mibragimchayev** [comment]
Following what we discussed: I'm all for this - I do think that we should provide documentation for both when possible.

**Comment by felicianotech** [comment]
Breaking this down into pieces. See OP for todo list.

**Comment by FelicianoTech** [comment]
Will continue at https://github.com/strawberry-tools/strawberry
